"""initial schema: items, price_snapshots, signals

Revision ID: c80ab7cf61a1
Revises: 
Create Date: 2026-07-13 23:45:52.807789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c80ab7cf61a1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_hash_name", sa.String(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("exterior", sa.String(), nullable=True),
        sa.Column("stattrak", sa.Boolean(), nullable=False),
        sa.Column("rarity", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_hash_name", name="uq_items_market_hash_name"),
    )
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_snapshots_item_collected",
        "price_snapshots",
        ["item_id", "collected_at"],
        unique=False,
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column(
            "signal_type",
            sa.Enum("FLIP", "INVESTMENT", name="signal_type"),
            nullable=False,
        ),
        sa.Column(
            "buy_price_suggested", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "sell_price_suggested", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "expected_profit_pct", sa.Numeric(precision=6, scale=2), nullable=False
        ),
        sa.Column("score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("spread_score", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("trend_score", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("liquidity_factor", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column(
            "volatility_penalty", sa.Numeric(precision=6, scale=4), nullable=True
        ),
        sa.Column("sent_to_telegram", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signals")
    op.drop_index("ix_price_snapshots_item_collected", table_name="price_snapshots")
    op.drop_table("price_snapshots")
    op.drop_table("items")
    # ### end Alembic commands ###
